
---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint # The name of the job
    runs-on: ubuntu-20.04 # The operating system on which the job will run
    steps:
      - name: Login to Docker Hub # Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout # Check out the code in the project directory, the purpose of this step is to get the code from the repository
        uses: actions/checkout@v2 # This is the action that allows you to check out the code in the project directory
      - name: Test # Run the tests
        run: docker compose run --rm app sh -c "python manage.py test" # This command runs the tests
      - name: Lint # Run the linter
        run: docker compose run --rm app sh -c "flake8" # This command runs the linter